### ISSUE TITLE
导航进度条有五个的上限，这是不是不太好

### ISSUE THREAD

**Issue by HW-hideonbush** [feiyangqingyun/qucsdk#7]
用起来就被局限了很多

**Comment by feiyangqingyun** [comment]
请仔细看头文件 setMaxStep

**Comment by HW-hideonbush** [comment]
> 请仔细看头文件 setMaxStep

试过了，是无效的，小于五个是可以控制的， 大于五个是不行的
![image](https://user-images.githubusercontent.com/67229194/94635362-0f384d80-0305-11eb-9efd-177c176adb6b.png)
![image](https://user-images.githubusercontent.com/67229194/94635395-26773b00-0305-11eb-9852-a931e93bda6e.png)

**Comment by feiyangqingyun** [comment]
setBottomInfo

**Comment by HW-hideonbush** [comment]
> setBottomInfo
并不行呢，应该是上限了

**Comment by HW-hideonbush** [comment]
> setBottomInfo

并不行呢，应该是上限了

**Comment by HW-hideonbush** [comment]
> setBottomInfo

setMaxStep(10)
getMaxStep()得到的值是5
是不是maxStep的值没有被修改
