### ISSUE TITLE
QT Creator 无法显示控件

### ISSUE THREAD

**Issue by whj4674672** [feiyangqingyun/qucsdk#8]
您好，目前我无法使用您提供的这些精美控件，您有空看下我的操作方法是否有误吗？
下载本仓库后，找到 `sdk_V20191226\qt_5_14_0_mingw730_64` 目录下的 quc.dll 文件。放到了，路径为 `C:\Qt\Qt5.14.0\5.14.0\mingw73_64\plugins\designer` 的目录下，然后打开 `designer.exe` 可以清晰的看到这些空间都可以进行拖拽操作后，把 `C:\Qt\Qt5.14.0\5.14.0\mingw73_64\plugins\designer` 目录下的 `quc.dll` 文件复制一份到 `C:\Qt\Qt5.14.0\Tools\QtCreator\bin\plugins\designer` 目录下，然后打开 `sdkdemo` 这个工程，可以正常运行之后，双击 ui 文件，无法看到控件显示，也无法进行拖拽操作，重启电脑后也无法显示。目前已在 两台电脑，分别尝试了 `QT 5.12.3` 和 `5.14.0` 两个版本的 mingw64位版本。

**Comment by feiyangqingyun** [comment]
请仔细看使用说明

**Comment by whj4674672** [comment]
感谢您的回答，问题已经解决，creator 里面必须放 mingw73_32 的 dll 才行。
